from PyQt5 import QtCore, QtGui, QtWidgets
from myPlotWidget import MyPlotWidget


ACC_YLIM = [-1.5, 1.5]
GYRO_YLIM = [-250, 250]
ANGLE_YLIM = [-180, 180]
F_YLIM = [-0.1, 1.1]

LABEL_SIZE_AXIS = 10
LABEL_SIZE_MED = 15


class Ui_MainWindow(object):
    def __init__(self, MainWindow):
        super().__init__()

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 676)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(10, 10, 1341, 611))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label_roll = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_roll.setFont(font)
        self.label_roll.setObjectName("label_roll")
        self.graphicsView_roll_t = MyPlotWidget(self.splitter, ylim=ANGLE_YLIM, xvar='time', yvar='angle')
        self.graphicsView_roll_t.setObjectName("graphicsView_roll_t")
        self.graphicsView_roll_f = MyPlotWidget(self.splitter, ylim=F_YLIM, xvar='freq', yvar='fft')
        self.graphicsView_roll_f.setObjectName("graphicsView_roll_f")
        self.label_pitch = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_pitch.setFont(font)
        self.label_pitch.setObjectName("label_pitch")
        self.graphicsView_pitch_t = MyPlotWidget(self.splitter, ylim=ANGLE_YLIM, xvar='time', yvar='fft')
        self.graphicsView_pitch_t.setObjectName("graphicsView_pitch_t")
        self.graphicsView_pitch_f = MyPlotWidget(self.splitter, ylim=F_YLIM, xvar='freq', yvar='fft')
        self.graphicsView_pitch_f.setObjectName("graphicsView_pitch_f")
        self.splitter.setSizes([20, 200, 200, 20, 200, 200])

        self.widget = QtWidgets.QWidget(self.splitter_2)
        self.splitter_2.setSizes([400, 1331-400])

        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView_gyro_z_f = MyPlotWidget(self.widget, ylim=F_YLIM, xvar='freq', yvar='fft')
        self.graphicsView_gyro_z_f.setObjectName("graphicsView_gyro_z_f")
        self.gridLayout.addWidget(self.graphicsView_gyro_z_f, 8, 2, 1, 1)
        self.graphicsView_gyro_x_f = MyPlotWidget(self.widget, ylim=F_YLIM, xvar='freq', yvar='fft')
        self.graphicsView_gyro_x_f.setObjectName("graphicsView_gyro_x_f")
        self.gridLayout.addWidget(self.graphicsView_gyro_x_f, 8, 0, 1, 1)
        self.label_gyro = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_gyro.setFont(font)
        self.label_gyro.setObjectName("label_gyro")
        self.gridLayout.addWidget(self.label_gyro, 5, 1, 1, 1)
        self.graphicsView_acc_z_t = MyPlotWidget(self.widget, ylim=ACC_YLIM, xvar='time', yvar='acc')
        self.graphicsView_acc_z_t.setObjectName("graphicsView_acc_z_t")
        self.gridLayout.addWidget(self.graphicsView_acc_z_t, 2, 2, 1, 1)
        self.label_acc_x = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(LABEL_SIZE_AXIS)
        self.label_acc_x.setFont(font)
        self.label_acc_x.setObjectName("label_acc_x")
        self.gridLayout.addWidget(self.label_acc_x, 1, 0, 1, 1)
        self.graphicsView_acc_y_f = MyPlotWidget(self.widget, ylim=F_YLIM, xvar='freq', yvar='fft')
        self.graphicsView_acc_y_f.setObjectName("graphicsView_acc_y_f")
        self.gridLayout.addWidget(self.graphicsView_acc_y_f, 3, 1, 1, 1)
        self.label_gyro_y = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(LABEL_SIZE_AXIS)
        self.label_gyro_y.setFont(font)
        self.label_gyro_y.setObjectName("label_gyro_y")
        self.gridLayout.addWidget(self.label_gyro_y, 6, 1, 1, 1)
        self.label_gyro_z = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(LABEL_SIZE_AXIS)
        self.label_gyro_z.setFont(font)
        self.label_gyro_z.setObjectName("label_gyro_z")
        self.gridLayout.addWidget(self.label_gyro_z, 6, 2, 1, 1)
        self.graphicsView_acc_x_t = MyPlotWidget(self.widget, ylim=ACC_YLIM, xvar='time', yvar='acc')
        self.graphicsView_acc_x_t.setObjectName("graphicsView_acc_x_t")
        self.gridLayout.addWidget(self.graphicsView_acc_x_t, 2, 0, 1, 1)
        self.graphicsView_acc_y_t = MyPlotWidget(self.widget, ylim=ACC_YLIM, xvar='time', yvar='acc')
        self.graphicsView_acc_y_t.setObjectName("graphicsView_acc_y_t")
        self.gridLayout.addWidget(self.graphicsView_acc_y_t, 2, 1, 1, 1)
        self.graphicsView_gyro_y_t = MyPlotWidget(self.widget, ylim=GYRO_YLIM, xvar='time', yvar='rate')
        self.graphicsView_gyro_y_t.setObjectName("graphicsView_gyro_y_t")
        self.gridLayout.addWidget(self.graphicsView_gyro_y_t, 7, 1, 1, 1)
        self.label_gyro_x = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(LABEL_SIZE_AXIS)
        self.label_gyro_x.setFont(font)
        self.label_gyro_x.setObjectName("label_gyro_x")
        self.gridLayout.addWidget(self.label_gyro_x, 6, 0, 1, 1)
        self.graphicsView_acc_z_f = MyPlotWidget(self.widget, ylim=F_YLIM, xvar='freq', yvar='fft')
        self.graphicsView_acc_z_f.setObjectName("graphicsView_acc_z_f")
        self.gridLayout.addWidget(self.graphicsView_acc_z_f, 3, 2, 1, 1)
        self.label_acc_y = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(LABEL_SIZE_AXIS)
        self.label_acc_y.setFont(font)
        self.label_acc_y.setObjectName("label_acc_y")
        self.gridLayout.addWidget(self.label_acc_y, 1, 1, 1, 1)
        self.graphicsView_acc_x_f = MyPlotWidget(self.widget, ylim=F_YLIM, xvar='freq', yvar='fft')
        self.graphicsView_acc_x_f.setObjectName("graphicsView_acc_x_f")
        self.gridLayout.addWidget(self.graphicsView_acc_x_f, 3, 0, 1, 1)
        self.graphicsView_gyro_x_t = MyPlotWidget(self.widget, ylim=GYRO_YLIM, xvar='time', yvar='rate')
        self.graphicsView_gyro_x_t.setObjectName("graphicsView_gyro_x_t")
        self.gridLayout.addWidget(self.graphicsView_gyro_x_t, 7, 0, 1, 1)
        self.graphicsView_gyro_y_f = MyPlotWidget(self.widget, ylim=F_YLIM, xvar='freq', yvar='fft')
        self.graphicsView_gyro_y_f.setObjectName("graphicsView_gyro_y_f")
        self.gridLayout.addWidget(self.graphicsView_gyro_y_f, 8, 1, 1, 1)
        self.graphicsView_gyro_z_t = MyPlotWidget(self.widget, ylim=GYRO_YLIM, xvar='time', yvar='rate')
        self.graphicsView_gyro_z_t.setObjectName("graphicsView_gyro_z_t")
        self.gridLayout.addWidget(self.graphicsView_gyro_z_t, 7, 2, 1, 1)
        self.label_acc = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_acc.setFont(font)
        self.label_acc.setObjectName("label_acc")
        self.gridLayout.addWidget(self.label_acc, 0, 1, 1, 1)
        self.label_acc_z = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(LABEL_SIZE_AXIS)
        self.label_acc_z.setFont(font)
        self.label_acc_z.setObjectName("label_acc_z")
        self.gridLayout.addWidget(self.label_acc_z, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1366, 21))
        self.menubar.setObjectName("menubar")
        self.menuConnect = QtWidgets.QMenu(self.menubar)
        self.menuConnect.setObjectName("menuConnect")
        self.menuPlot = QtWidgets.QMenu(self.menubar)
        self.menuPlot.setObjectName("menuPlot")
        MainWindow.setMenuBar(self.menubar)
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setCheckable(True)
        self.actionConnect.setObjectName("actionConnect")
        self.actionRun = QtWidgets.QAction(MainWindow)
        self.actionRun.setCheckable(True)
        self.actionRun.setObjectName("actionRun")
        self.actionRun.setChecked(False)
        self.actionInfo = QtWidgets.QAction(MainWindow)
        self.actionInfo.setObjectName('actionInfo')
        self.menuConnect.addAction(self.actionConnect)
        self.menuHelp.addAction(self.actionInfo)
        self.menuPlot.addAction(self.actionRun)
        self.menubar.addAction(self.menuConnect.menuAction())
        self.menubar.addAction(self.menuPlot.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sensor Fusion"))
        self.label_roll.setText(_translate("MainWindow", "Roll (x)"))
        self.label_pitch.setText(_translate("MainWindow", "Pitch (y)"))
        self.label_gyro.setText(_translate("MainWindow", "Gyroscope"))
        self.label_acc.setText(_translate("MainWindow", "Accelerometer"))
        self.label_acc_x.setText(_translate("MainWindow", "X"))
        self.label_acc_y.setText(_translate("MainWindow", "Y"))
        self.label_acc_z.setText(_translate("MainWindow", "Z"))
        self.label_gyro_x.setText(_translate("MainWindow", "X"))
        self.label_gyro_y.setText(_translate("MainWindow", "Y"))
        self.label_gyro_z.setText(_translate("MainWindow", "Z"))
        self.menuConnect.setTitle(_translate("MainWindow", "Settings"))
        self.menuPlot.setTitle(_translate("MainWindow", "Plot"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionConnect.setText(_translate("MainWindow", "Connect"))
        self.actionRun.setText(_translate("MainWindow", "Run"))
        self.actionInfo.setText(_translate("MainWindow", "Info"))
